name: Testing unit_test without Nondex tool.
run-name: Testing unit_test without Nondex tool.
on: [push]
jobs:
  Testing-without-Nondex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile with Maven
      run: mvn clean install -DskipTests -pl "modules/sql-engine" -am
    - name: Run test without Nondex tool
      run: mvn -pl emodules/sql-engine test -Dtest=org.apache.ignite.internal.sql.engine.exec.MockedStructuresTest#testCreateTable
